scsi: ufs: Fix derp in commit 992203a7c0d58bfb160a2a648134773583132117
../drivers/scsi/ufs/ufshcd.c: In function ‘ufshcd_queuecommand’:
../drivers/scsi/ufs/ufshcd.c:3112:3: error: too few arguments to function ‘ufshcd_release’
   ufshcd_release(hba);
   ^~~~~~~~~~~~~~
../drivers/scsi/ufs/ufshcd.c:1656:6: note: declared here
 void ufshcd_release(struct ufs_hba *hba, bool no_sched)
      ^~~~~~~~~~~~~~

Signed-off-by: Fiqri Ardyansyah <fiqri15072019@gmail.com>